#!/bin/bash
#
# @file install
# @brief Install carrybag items into the given directory
# @author Alister Lewis-Bowen <alister@different.com>
# @requires color (http://code.google.com/p/ansi-color/)

BASE="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PWD="$(pwd)"
OPTN=$1

function clean {
    ls -la | grep "^l" | grep "/carrybag/" | awk '{print $9}' | cut -d'@' -f1 \
        | xargs rm
}

function link {
    for file in $(ls -Ad $BASE/$1); do
        ln -sf $file &>/dev/null
    done
}

case "$OPTN" in
    -h|--help)
        echo "
Bootstrap installer for carrybag dotfiles and scripts.

Usage:
$(color bd)install$(color) [ $(color ul)-d$(color)$(color bd) \
| $(color ul)-s$(color)$(color bd) | $(color ul)-c$(color)$(color bd)] \
$(color)

Options:
$(color ul)-d$(color) install the dot files
$(color ul)-s$(color) install the script files
$(color ul)-c$(color) delete any sym'linked carrybag items
";
        ;;
    -c|--clean)
        cd ~ && clean && cd ~/bin && clean
        ;;
    -d|--dot-files)
        cd ~ && clean && link dot_files/.* && source .bashrc
        ;;
    -s|--scripts)
        cd ~/bin && clean && link scripts/*
        ;;
    *)
        install -d && install -s
        ;;
esac

cd $PWD
