#!/bin/bash
#
# @file install
# ★  Unpack the carrybag into the correct places.
# Note that the items are sym'linked back to the source dir and not copied.
# @author Alister Lewis-Bowen <alister@different.com>

BASE=$( cd "$( dirname "$0" )" && pwd )
PWD=$(pwd)
OPTN=$1
unset helpCommand
unset helpSummary

function _clean {
    ls -la | grep "^l" | grep "/carrybag/" | awk '{print $9}' | cut -d'@' -f1 \
        | xargs rm 2>/dev/null
}

function _link {
    for file in $(ls -Ad $BASE/$1); do
        ln -sf $file &>/dev/null
    done
}

case "$OPTN" in
    -h|--help)
        echo "
Bootstrap installer for carrybag

Usage:
install [ -d | -s | -c ]

Options:
-d install the dot files
-s install the script files
-c delete any installed carrybag items
";
        ;;
    -c|--clean)
        cd ~ && _clean
        cd ~/bin && _clean
        ;;
    -d|--dot-files)
        cd ~ && _clean
        _link dot_files/.*
        source .bashrc
        ;;
    -s|--scripts)
        [ ! -d ~/bin ] && mkdir ~/bin
        cd ~/bin && _clean
        _link scripts/*
        ;;
    *)
        $BASE/install -d
        $BASE/install -s
        ;;
esac

cd $PWD
