#!/bin/bash
# ----------------------------------------------------------------------------
# @file notes
# Simple notebook
# @see rcs
# @see color
# @author Alister Lewis-Bowen [alister@different.com]
# ----------------------------------------------------------------------------
# This software is distributed under the the MIT License.
#
# Copyright (c) 2008 Alister Lewis-Bowen
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
# ----------------------------------------------------------------------------

EDITOR=${EDITOR:-'vi'};
NOTEBOOK=~/.NOTES;
RCS=`dirname $NOTEBOOK`/RCS;

# Function: Help
# ----------------------------------------------------------------------------

function help {
	echo;
	echo "$(color bd)Simple notebook$(color)";
	echo;
	echo 'Usage:';
	echo "$(color bd)notes$(color) [ add | edit | help | list ]";
	echo;
	echo 'where:';
	echo "$(color bd)notes add$(color) adds an entry section to the notebook";
	echo "$(color bd)notes edit$(color) edits the notebook";
	echo "$(color bd)notes help$(color) provides this help text";
	echo "$(color bd)notes list$(color) or just $(color bd)notes$(color) displays the notebook";
	echo;
	exit 1;
}

# Create notebook file under RCS control
# ----------------------------------------------------------------------------

if [ ! -e $NOTEBOOK ]; then 
	echo -e "\n$(color bd green)Unable to find $NOTEBOOK. No problem. I'll create one for you...$(color nm green)";
	touch $NOTEBOOK;
	echo > $NOTEBOOK;
	echo "|=========|=========|=========|=========|=========|=========|=========" >> $NOTEBOOK;
	echo "0         1         2         3         4         5         7         " >> $NOTEBOOK;
	echo "======================================================================" >> $NOTEBOOK;
	echo '$Id$' >> $NOTEBOOK;
	chmod 644 $NOTEBOOK;
	if [ ! -d $RCS ]; then mkdir -p $RCS; fi;
	ci $NOTEBOOK;
	co $NOTEBOOK;
	echo -n "$(color bd)Your new notebook is ready. ";
	echo -n "Now use $(color white)notes a$(color green) to add a new section. ";
	echo "Use $(color white)notes e$(color green) to modify your notebook content...$(color)";
	exit 0;
fi;

# Parse command line options
# ----------------------------------------------------------------------------
	
case "$1" in
	add | a )
		co -l $NOTEBOOK;
		cp $NOTEBOOK /tmp/notebook;
		echo " --------- --------- --------- --------- --------- --------- ---------" > $NOTEBOOK;
		echo -e "NEW SECTION TITLE:\n\n" >> $NOTEBOOK;
		cat /tmp/notebook >> $NOTEBOOK;
		rm /tmp/notebook;
		$EDITOR $NOTEBOOK;
		ci $NOTEBOOK;
		co $NOTEBOOK;
		;;		
	edit | e )
		co -l $NOTEBOOK;
		$EDITOR $NOTEBOOK;
		ci $NOTEBOOK;
		co $NOTEBOOK;
		;;
	help | h | -h | --help )	
		help;
		;;
	*)		
		cat $NOTEBOOK;
		;;
esac;

exit 0;