#!/bin/bash
# @file thirdparty
# @brief Configure dependencies on 3rd party packages
# @author Alister Lewis-Bowen <alister@different.com>
# @see .thirdpartypackages

PACKAGE_DIR=~/.thirdpartypackages

for file in {autoload,bitmaps,colors,doc,syntax,ftdetect,ftplugin}; do
    [ ! -d ~/.vim/$file ] && mkdir -p ~/.vim/$file
done

#
# bash script color and formating
#

ln -sf $PACKAGE_DIR/ansi-color/ansi-color/color ~/bin/color

#
# solarized theme for vim and cmd line
#

for file in {autoload/togglebg.vim,bitmaps/togglebg.png,colors/solarized.vim,doc/solarized.txt,doc/tags}; do
    ln -sf $PACKAGE_DIR/solarized/vim-colors-solarized/$file ~/.vim/$file
done
ln -sf $PACKAGE_DIR/solarized/xresources-colors-solarized/Xresources ~/.Xdefaults
ln -sf $PACKAGE_DIR/solarized/xresources-colors-solarized/Xresources ~/.Xresources

#
# NERDTree for vim
#

for file in {doc/NERD_tree.txt,plugin/NERD_tree.vim,syntax/nerdtree.vim}; do
    ln -sf $PACKAGE_DIR/nerdtree/$file ~/.vim/$file
done
ln -sf $PACKAGE_DIR/nerdtree/nerdtree_plugin ~/.vim/nerdtree_plugin

#
# actionscript for vim
#

ln -sf $PACKAGE_DIR/actionscript.vim/syntax/actionscript.vim ~/.vim/syntax/actionscript.vim

#
# jshint for vim
#
# ● Assumes https://github.com/jshint/jshint is installed
#

for file in {plugin/jshint.vim,doc/jshint.txt}; do
    ln -sf $PACKAGE_DIR/jshint.vim/$file ~/.vim/$file
done

#
# markdown for vim
#

for file in {ftdetect/markdown.vim,ftplugin/markdown.vim,syntax/markdown.vim}; do
    ln -sf $PACKAGE_DIR/vim-markdown/$file ~/.vim/$file
done
