#!/bin/bash
# @file meetingAlert
# Look for meetings on now or in 15 minutes and record state as a simple
# character in the ~/.meetingAlert file
# @author Alister Lewis-Bowen <alister@different.com>

state=~/.meetingAlert
[ -e /usr/local/bin/icalBuddy ] && {
    [[ -n $(icalBuddy -ea -li 1 -f eventsFrom:"$(date -v+15M)" to:"$(date -v+2M)") ]] && \
        echo -n '★ ' >$state || echo -n '☆ ' >$state
} || {
    echo -n '' >$state
}
