#!/bin/bash
#
# Remove OSX extended attributes from a file or directory
#
# Copyright (c) 2011 Alister Lewis-Bowen <alister@different.com>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.
#

case $1 in
    -h|--help)
        echo "
Remove OSX extended attributes from a file or directory

usage:
$(color bd)rmxattr$(color) [options] $(color ul)target$(color)

where:
$(color ul)target$(color) is a file or directory

options:
$(color bd)-h$(color), $(color bd)--help$(color) shows this help
$(color bd)-d$(color), $(color bd)--dir$(color) remove any attributes found in the given directory
No options assumes that the target is a file and any attributes on this file will be removed
"
        ;;
    -d|--dir)
        find $2 -maxdepth 1 -mindepth 1 -name "*" | while read file ; do
            xattr -d $(xattr "$file") "$file" &> /dev/null
        done
        ;;
    *)
        xattr -d $(xattr "$1") "$1" &> /dev/null
        ;;
esac

