#!/bin/bash
#
# @file rmxattr
# Remove OSX extended attributes from a file or directory
# @author Alister Lewis-Bowen <alister@different.com>
#

case $1 in
    -h|--help)
        echo "
Remove OSX extended attributes from a file or directory

usage:
$(color bd)rmxattr$(color) [options] $(color ul)target$(color)

where:
$(color ul)target$(color) is a file or directory

options:
$(color bd)-h$(color), $(color bd)--help$(color) shows this help
$(color bd)-d$(color), $(color bd)--dir$(color) remove any attributes found in the given directory
No options assumes that the target is a file and any attributes on this file will be removed
"
        ;;
    -d|--dir)
        find $2 -maxdepth 1 -mindepth 1 -name "*" | while read file ; do
            xattr -d $(xattr "$file") "$file" &> /dev/null
        done
        ;;
    *)
        xattr -d $(xattr "$1") "$1" &> /dev/null
        ;;
esac

