#!/bin/sh

CURL='curl -s --header User-Agent:alb/1.0';
URL="http://www.google.com/search";
QUERY=$(echo "$@" | sed -e 's/+/%2B/g' -e 's/ /+/g');
echo $CURL "$URL?q=weather%2B$QUERY"

result=$(
    $CURL "$URL?q=weather%2B$QUERY" |
    grep '<table class="ts std' |
    perl -pe 's@.*<table class="ts std.*?<b>(.*?)</b>.*@\1@'
    #perl -pe 's@\x{a0}@@g' |
    #perl -pe 's@ </font>@@g' |
    #perl -pe 's@<.*?>@@g'
);

echo $result;
